<?php
namespace Dnetix\Files;

class MimeTypes {

    const APPLICATION_ACAD = 'application/acad';
    const APPLICATION_ARJ = 'application/arj';
    const APPLICATION_BASE64 = 'application/base64';
    const APPLICATION_BINHEX = 'application/binhex';
    const APPLICATION_BINHEX4 = 'application/binhex4';
    const APPLICATION_BOOK = 'application/book';
    const APPLICATION_CDF = 'application/cdf';
    const APPLICATION_CLARISCAD = 'application/clariscad';
    const APPLICATION_COMMONGROUND = 'application/commonground';
    const APPLICATION_DRAFTING = 'application/drafting';
    const APPLICATION_DSPTYPE = 'application/dsptype';
    const APPLICATION_DXF = 'application/dxf';
    const APPLICATION_ECMASCRIPT = 'application/ecmascript';
    const APPLICATION_ENVOY = 'application/envoy';
    const APPLICATION_EXCEL = 'application/excel';
    const APPLICATION_FRACTALS = 'application/fractals';
    const APPLICATION_FREELOADER = 'application/freeloader';
    const APPLICATION_FUTURESPLASH = 'application/futuresplash';
    const APPLICATION_GNUTAR = 'application/gnutar';
    const APPLICATION_GROUPWISE = 'application/groupwise';
    const APPLICATION_HLP = 'application/hlp';
    const APPLICATION_HTA = 'application/hta';
    const APPLICATION_I_DEAS = 'application/i-deas';
    const APPLICATION_IGES = 'application/iges';
    const APPLICATION_INF = 'application/inf';
    const APPLICATION_JAVA = 'application/java';
    const APPLICATION_JAVA_BYTE_CODE = 'application/java-byte-code';
    const APPLICATION_JAVASCRIPT = 'application/javascript';
    const APPLICATION_LHA = 'application/lha';
    const APPLICATION_LZX = 'application/lzx';
    const APPLICATION_MAC_BINARY = 'application/mac-binary';
    const APPLICATION_MAC_BINHEX = 'application/mac-binhex';
    const APPLICATION_MAC_BINHEX40 = 'application/mac-binhex40';
    const APPLICATION_MAC_COMPACTPRO = 'application/mac-compactpro';
    const APPLICATION_MACBINARY = 'application/macbinary';
    const APPLICATION_MARC = 'application/marc';
    const APPLICATION_MBEDLET = 'application/mbedlet';
    const APPLICATION_MCAD = 'application/mcad';
    const APPLICATION_MIME = 'application/mime';
    const APPLICATION_MSPOWERPOINT = 'application/mspowerpoint';
    const APPLICATION_MSWORD = 'application/msword';
    const APPLICATION_MSWRITE = 'application/mswrite';
    const APPLICATION_NETMC = 'application/netmc';
    const APPLICATION_OCTET_STREAM = 'application/octet-stream';
    const APPLICATION_ODA = 'application/oda';
    const APPLICATION_PDF = 'application/pdf';
    const APPLICATION_PKCS_12 = 'application/pkcs-12';
    const APPLICATION_PKCS_CRL = 'application/pkcs-crl';
    const APPLICATION_PKCS10 = 'application/pkcs10';
    const APPLICATION_PKCS7_MIME = 'application/pkcs7-mime';
    const APPLICATION_PKCS7_SIGNATURE = 'application/pkcs7-signature';
    const APPLICATION_PKIX_CERT = 'application/pkix-cert';
    const APPLICATION_PKIX_CRL = 'application/pkix-crl';
    const APPLICATION_PLAIN = 'application/plain';
    const APPLICATION_POSTSCRIPT = 'application/postscript';
    const APPLICATION_POWERPOINT = 'application/powerpoint';
    const APPLICATION_PRO_ENG = 'application/pro_eng';
    const APPLICATION_RINGING_TONES = 'application/ringing-tones';
    const APPLICATION_RTF = 'application/rtf';
    const APPLICATION_SDP = 'application/sdp';
    const APPLICATION_SEA = 'application/sea';
    const APPLICATION_SET = 'application/set';
    const APPLICATION_SLA = 'application/sla';
    const APPLICATION_SMIL = 'application/smil';
    const APPLICATION_SOLIDS = 'application/solids';
    const APPLICATION_SOUNDER = 'application/sounder';
    const APPLICATION_STEP = 'application/step';
    const APPLICATION_STREAMINGMEDIA = 'application/streamingmedia';
    const APPLICATION_TOOLBOOK = 'application/toolbook';
    const APPLICATION_VDA = 'application/vda';
    const APPLICATION_VNDFDF = 'application/vnd.fdf';
    const APPLICATION_VNDHP_HPGL = 'application/vnd.hp-hpgl';
    const APPLICATION_VNDHP_PCL = 'application/vnd.hp-pcl';
    const APPLICATION_VNDMS_EXCEL = 'application/vnd.ms-excel';
    const APPLICATION_VNDMS_PKICERTSTORE = 'application/vnd.ms-pki.certstore';
    const APPLICATION_VNDMS_PKIPKO = 'application/vnd.ms-pki.pko';
    const APPLICATION_VNDMS_PKISECCAT = 'application/vnd.ms-pki.seccat';
    const APPLICATION_VNDMS_PKISTL = 'application/vnd.ms-pki.stl';
    const APPLICATION_VNDMS_POWERPOINT = 'application/vnd.ms-powerpoint';
    const APPLICATION_VNDMS_PROJECT = 'application/vnd.ms-project';
    const APPLICATION_VNDNOKIACONFIGURATION_MESSAGE = 'application/vnd.nokia.configuration-message';
    const APPLICATION_VNDNOKIARINGING_TONE = 'application/vnd.nokia.ringing-tone';
    const APPLICATION_VNDRN_REALMEDIA = 'application/vnd.rn-realmedia';
    const APPLICATION_VNDRN_REALPLAYER = 'application/vnd.rn-realplayer';
    const APPLICATION_VNDWAPWMLC = 'application/vnd.wap.wmlc';
    const APPLICATION_VNDWAPWMLSCRIPTC = 'application/vnd.wap.wmlscriptc';
    const APPLICATION_VNDXARA = 'application/vnd.xara';
    const APPLICATION_VOCALTEC_MEDIA_DESC = 'application/vocaltec-media-desc';
    const APPLICATION_VOCALTEC_MEDIA_FILE = 'application/vocaltec-media-file';
    const APPLICATION_WORDPERFECT = 'application/wordperfect';
    const APPLICATION_WORDPERFECT60 = 'application/wordperfect6.0';
    const APPLICATION_WORDPERFECT61 = 'application/wordperfect6.1';
    const APPLICATION_X_123 = 'application/x-123';
    const APPLICATION_X_AIM = 'application/x-aim';
    const APPLICATION_X_AUTHORWARE_BIN = 'application/x-authorware-bin';
    const APPLICATION_X_AUTHORWARE_MAP = 'application/x-authorware-map';
    const APPLICATION_X_AUTHORWARE_SEG = 'application/x-authorware-seg';
    const APPLICATION_X_BCPIO = 'application/x-bcpio';
    const APPLICATION_X_BINARY = 'application/x-binary';
    const APPLICATION_X_BINHEX40 = 'application/x-binhex40';
    const APPLICATION_X_BSH = 'application/x-bsh';
    const APPLICATION_X_BYTECODEPYTHON = 'application/x-bytecode.python';
    const APPLICATION_X_BZIP = 'application/x-bzip';
    const APPLICATION_X_BZIP2 = 'application/x-bzip2';
    const APPLICATION_X_CDF = 'application/x-cdf';
    const APPLICATION_X_CDLINK = 'application/x-cdlink';
    const APPLICATION_X_CHAT = 'application/x-chat';
    const APPLICATION_X_CMU_RASTER = 'application/x-cmu-raster';
    const APPLICATION_X_COCOA = 'application/x-cocoa';
    const APPLICATION_X_COMPACTPRO = 'application/x-compactpro';
    const APPLICATION_X_COMPRESS = 'application/x-compress';
    const APPLICATION_X_COMPRESSED = 'application/x-compressed';
    const APPLICATION_X_CONFERENCE = 'application/x-conference';
    const APPLICATION_X_CPIO = 'application/x-cpio';
    const APPLICATION_X_CPT = 'application/x-cpt';
    const APPLICATION_X_CSH = 'application/x-csh';
    const APPLICATION_X_DEEPV = 'application/x-deepv';
    const APPLICATION_X_DIRECTOR = 'application/x-director';
    const APPLICATION_X_DVI = 'application/x-dvi';
    const APPLICATION_X_ELC = 'application/x-elc';
    const APPLICATION_X_ENVOY = 'application/x-envoy';
    const APPLICATION_X_ESREHBER = 'application/x-esrehber';
    const APPLICATION_X_EXCEL = 'application/x-excel';
    const APPLICATION_X_FRAME = 'application/x-frame';
    const APPLICATION_X_FREELANCE = 'application/x-freelance';
    const APPLICATION_X_GSP = 'application/x-gsp';
    const APPLICATION_X_GSS = 'application/x-gss';
    const APPLICATION_X_GTAR = 'application/x-gtar';
    const APPLICATION_X_GZIP = 'application/x-gzip';
    const APPLICATION_X_HDF = 'application/x-hdf';
    const APPLICATION_X_HELPFILE = 'application/x-helpfile';
    const APPLICATION_X_HTTPD_IMAP = 'application/x-httpd-imap';
    const APPLICATION_X_IMA = 'application/x-ima';
    const APPLICATION_X_INTERNETT_SIGNUP = 'application/x-internett-signup';
    const APPLICATION_X_INVENTOR = 'application/x-inventor';
    const APPLICATION_X_IP2 = 'application/x-ip2';
    const APPLICATION_X_JAVA_CLASS = 'application/x-java-class';
    const APPLICATION_X_JAVA_COMMERCE = 'application/x-java-commerce';
    const APPLICATION_X_JAVASCRIPT = 'application/x-javascript';
    const APPLICATION_X_KOAN = 'application/x-koan';
    const APPLICATION_X_KSH = 'application/x-ksh';
    const APPLICATION_X_LATEX = 'application/x-latex';
    const APPLICATION_X_LHA = 'application/x-lha';
    const APPLICATION_X_LISP = 'application/x-lisp';
    const APPLICATION_X_LIVESCREEN = 'application/x-livescreen';
    const APPLICATION_X_LOTUS = 'application/x-lotus';
    const APPLICATION_X_LOTUSSCREENCAM = 'application/x-lotusscreencam';
    const APPLICATION_X_LZH = 'application/x-lzh';
    const APPLICATION_X_LZX = 'application/x-lzx';
    const APPLICATION_X_MAC_BINHEX40 = 'application/x-mac-binhex40';
    const APPLICATION_X_MACBINARY = 'application/x-macbinary';
    const APPLICATION_X_MATHCAD = 'application/x-mathcad';
    const APPLICATION_X_MEME = 'application/x-meme';
    const APPLICATION_X_MIDI = 'application/x-midi';
    const APPLICATION_X_MIF = 'application/x-mif';
    const APPLICATION_X_MIX_TRANSFER = 'application/x-mix-transfer';
    const APPLICATION_X_MPLAYER2 = 'application/x-mplayer2';
    const APPLICATION_X_MSEXCEL = 'application/x-msexcel';
    const APPLICATION_X_MSPOWERPOINT = 'application/x-mspowerpoint';
    const APPLICATION_X_NAVI_ANIMATION = 'application/x-navi-animation';
    const APPLICATION_X_NAVIDOC = 'application/x-navidoc';
    const APPLICATION_X_NAVIMAP = 'application/x-navimap';
    const APPLICATION_X_NAVISTYLE = 'application/x-navistyle';
    const APPLICATION_X_NETCDF = 'application/x-netcdf';
    const APPLICATION_X_NEWTON_COMPATIBLE_PKG = 'application/x-newton-compatible-pkg';
    const APPLICATION_X_NOKIA_9000_COMMUNICATOR_ADD_ON_SOFTWARE = 'application/x-nokia-9000-communicator-add-on-software';
    const APPLICATION_X_OMC = 'application/x-omc';
    const APPLICATION_X_OMCDATAMAKER = 'application/x-omcdatamaker';
    const APPLICATION_X_OMCREGERATOR = 'application/x-omcregerator';
    const APPLICATION_X_PAGEMAKER = 'application/x-pagemaker';
    const APPLICATION_X_PCL = 'application/x-pcl';
    const APPLICATION_X_PIXCLSCRIPT = 'application/x-pixclscript';
    const APPLICATION_X_PKCS10 = 'application/x-pkcs10';
    const APPLICATION_X_PKCS12 = 'application/x-pkcs12';
    const APPLICATION_X_PKCS7_CERTIFICATES = 'application/x-pkcs7-certificates';
    const APPLICATION_X_PKCS7_CERTREQRESP = 'application/x-pkcs7-certreqresp';
    const APPLICATION_X_PKCS7_MIME = 'application/x-pkcs7-mime';
    const APPLICATION_X_PKCS7_SIGNATURE = 'application/x-pkcs7-signature';
    const APPLICATION_X_POINTPLUS = 'application/x-pointplus';
    const APPLICATION_X_PORTABLE_ANYMAP = 'application/x-portable-anymap';
    const APPLICATION_X_PROJECT = 'application/x-project';
    const APPLICATION_X_QPRO = 'application/x-qpro';
    const APPLICATION_X_RTF = 'application/x-rtf';
    const APPLICATION_X_SDP = 'application/x-sdp';
    const APPLICATION_X_SEA = 'application/x-sea';
    const APPLICATION_X_SEELOGO = 'application/x-seelogo';
    const APPLICATION_X_SH = 'application/x-sh';
    const APPLICATION_X_SHAR = 'application/x-shar';
    const APPLICATION_X_SHOCKWAVE_FLASH = 'application/x-shockwave-flash';
    const APPLICATION_X_SIT = 'application/x-sit';
    const APPLICATION_X_SPRITE = 'application/x-sprite';
    const APPLICATION_X_STUFFIT = 'application/x-stuffit';
    const APPLICATION_X_SV4CPIO = 'application/x-sv4cpio';
    const APPLICATION_X_SV4CRC = 'application/x-sv4crc';
    const APPLICATION_X_TAR = 'application/x-tar';
    const APPLICATION_X_TBOOK = 'application/x-tbook';
    const APPLICATION_X_TCL = 'application/x-tcl';
    const APPLICATION_X_TEX = 'application/x-tex';
    const APPLICATION_X_TEXINFO = 'application/x-texinfo';
    const APPLICATION_X_TROFF = 'application/x-troff';
    const APPLICATION_X_TROFF_MAN = 'application/x-troff-man';
    const APPLICATION_X_TROFF_ME = 'application/x-troff-me';
    const APPLICATION_X_TROFF_MS = 'application/x-troff-ms';
    const APPLICATION_X_TROFF_MSVIDEO = 'application/x-troff-msvideo';
    const APPLICATION_X_USTAR = 'application/x-ustar';
    const APPLICATION_X_VISIO = 'application/x-visio';
    const APPLICATION_X_VNDAUDIOEXPLOSIONMZZ = 'application/x-vnd.audioexplosion.mzz';
    const APPLICATION_X_VNDLS_XPIX = 'application/x-vnd.ls-xpix';
    const APPLICATION_X_VRML = 'application/x-vrml';
    const APPLICATION_X_WAIS_SOURCE = 'application/x-wais-source';
    const APPLICATION_X_WINHELP = 'application/x-winhelp';
    const APPLICATION_X_WINTALK = 'application/x-wintalk';
    const APPLICATION_X_WORLD = 'application/x-world';
    const APPLICATION_X_WPWIN = 'application/x-wpwin';
    const APPLICATION_X_WRI = 'application/x-wri';
    const APPLICATION_X_X509_CA_CERT = 'application/x-x509-ca-cert';
    const APPLICATION_X_X509_USER_CERT = 'application/x-x509-user-cert';
    const APPLICATION_X_ZIP_COMPRESSED = 'application/x-zip-compressed';
    const APPLICATION_XML = 'application/xml';
    const APPLICATION_ZIP = 'application/zip';
    const AUDIO_AIFF = 'audio/aiff';
    const AUDIO_BASIC = 'audio/basic';
    const AUDIO_IT = 'audio/it';
    const AUDIO_MAKE = 'audio/make';
    const AUDIO_MAKEMYFUNK = 'audio/make.my.funk';
    const AUDIO_MID = 'audio/mid';
    const AUDIO_MIDI = 'audio/midi';
    const AUDIO_MOD = 'audio/mod';
    const AUDIO_MPEG = 'audio/mpeg';
    const AUDIO_MPEG3 = 'audio/mpeg3';
    const AUDIO_NSPAUDIO = 'audio/nspaudio';
    const AUDIO_S3M = 'audio/s3m';
    const AUDIO_TSP_AUDIO = 'audio/tsp-audio';
    const AUDIO_TSPLAYER = 'audio/tsplayer';
    const AUDIO_VNDQCELP = 'audio/vnd.qcelp';
    const AUDIO_VOC = 'audio/voc';
    const AUDIO_VOXWARE = 'audio/voxware';
    const AUDIO_WAV = 'audio/wav';
    const AUDIO_X_ADPCM = 'audio/x-adpcm';
    const AUDIO_X_AIFF = 'audio/x-aiff';
    const AUDIO_X_AU = 'audio/x-au';
    const AUDIO_X_GSM = 'audio/x-gsm';
    const AUDIO_X_JAM = 'audio/x-jam';
    const AUDIO_X_LIVEAUDIO = 'audio/x-liveaudio';
    const AUDIO_X_MID = 'audio/x-mid';
    const AUDIO_X_MIDI = 'audio/x-midi';
    const AUDIO_X_MOD = 'audio/x-mod';
    const AUDIO_X_MPEG = 'audio/x-mpeg';
    const AUDIO_X_MPEG_3 = 'audio/x-mpeg-3';
    const AUDIO_X_MPEQURL = 'audio/x-mpequrl';
    const AUDIO_X_NSPAUDIO = 'audio/x-nspaudio';
    const AUDIO_X_PN_REALAUDIO = 'audio/x-pn-realaudio';
    const AUDIO_X_PN_REALAUDIO_PLUGIN = 'audio/x-pn-realaudio-plugin';
    const AUDIO_X_PSID = 'audio/x-psid';
    const AUDIO_X_REALAUDIO = 'audio/x-realaudio';
    const AUDIO_X_TWINVQ = 'audio/x-twinvq';
    const AUDIO_X_TWINVQ_PLUGIN = 'audio/x-twinvq-plugin';
    const AUDIO_X_VNDAUDIOEXPLOSIONMJUICEMEDIAFILE = 'audio/x-vnd.audioexplosion.mjuicemediafile';
    const AUDIO_X_VOC = 'audio/x-voc';
    const AUDIO_X_WAV = 'audio/x-wav';
    const AUDIO_XM = 'audio/xm';
    const CHEMICAL_X_PDB = 'chemical/x-pdb';
    const I_WORLD_I_VRML = 'i-world/i-vrml';
    const IMAGE_BMP = 'image/bmp';
    const IMAGE_CMU_RASTER = 'image/cmu-raster';
    const IMAGE_FIF = 'image/fif';
    const IMAGE_FLORIAN = 'image/florian';
    const IMAGE_G3FAX = 'image/g3fax';
    const IMAGE_GIF = 'image/gif';
    const IMAGE_IEF = 'image/ief';
    const IMAGE_JPEG = 'image/jpeg';
    const IMAGE_JUTVISION = 'image/jutvision';
    const IMAGE_NAPLPS = 'image/naplps';
    const IMAGE_PICT = 'image/pict';
    const IMAGE_PJPEG = 'image/pjpeg';
    const IMAGE_PNG = 'image/png';
    const IMAGE_TIFF = 'image/tiff';
    const IMAGE_VASA = 'image/vasa';
    const IMAGE_VNDDWG = 'image/vnd.dwg';
    const IMAGE_VNDFPX = 'image/vnd.fpx';
    const IMAGE_VNDNET_FPX = 'image/vnd.net-fpx';
    const IMAGE_VNDRN_REALFLASH = 'image/vnd.rn-realflash';
    const IMAGE_VNDRN_REALPIX = 'image/vnd.rn-realpix';
    const IMAGE_VNDWAPWBMP = 'image/vnd.wap.wbmp';
    const IMAGE_VNDXIFF = 'image/vnd.xiff';
    const IMAGE_X_CMU_RASTER = 'image/x-cmu-raster';
    const IMAGE_X_DWG = 'image/x-dwg';
    const IMAGE_X_ICON = 'image/x-icon';
    const IMAGE_X_JG = 'image/x-jg';
    const IMAGE_X_JPS = 'image/x-jps';
    const IMAGE_X_NIFF = 'image/x-niff';
    const IMAGE_X_PCX = 'image/x-pcx';
    const IMAGE_X_PICT = 'image/x-pict';
    const IMAGE_X_PORTABLE_ANYMAP = 'image/x-portable-anymap';
    const IMAGE_X_PORTABLE_BITMAP = 'image/x-portable-bitmap';
    const IMAGE_X_PORTABLE_GRAYMAP = 'image/x-portable-graymap';
    const IMAGE_X_PORTABLE_GREYMAP = 'image/x-portable-greymap';
    const IMAGE_X_PORTABLE_PIXMAP = 'image/x-portable-pixmap';
    const IMAGE_X_QUICKTIME = 'image/x-quicktime';
    const IMAGE_X_RGB = 'image/x-rgb';
    const IMAGE_X_TIFF = 'image/x-tiff';
    const IMAGE_X_WINDOWS_BMP = 'image/x-windows-bmp';
    const IMAGE_X_XBITMAP = 'image/x-xbitmap';
    const IMAGE_X_XBM = 'image/x-xbm';
    const IMAGE_X_XPIXMAP = 'image/x-xpixmap';
    const IMAGE_X_XWD = 'image/x-xwd';
    const IMAGE_X_XWINDOWDUMP = 'image/x-xwindowdump';
    const IMAGE_XBM = 'image/xbm';
    const IMAGE_XPM = 'image/xpm';
    const MESSAGE_RFC822 = 'message/rfc822';
    const MODEL_IGES = 'model/iges';
    const MODEL_VNDDWF = 'model/vnd.dwf';
    const MODEL_VRML = 'model/vrml';
    const MODEL_X_POV = 'model/x-pov';
    const MULTIPART_X_GZIP = 'multipart/x-gzip';
    const MULTIPART_X_USTAR = 'multipart/x-ustar';
    const MULTIPART_X_ZIP = 'multipart/x-zip';
    const MUSIC_CRESCENDO = 'music/crescendo';
    const MUSIC_X_KARAOKE = 'music/x-karaoke';
    const PALEOVU_X_PV = 'paleovu/x-pv';
    const TEXT_ASP = 'text/asp';
    const TEXT_CSS = 'text/css';
    const TEXT_ECMASCRIPT = 'text/ecmascript';
    const TEXT_HTML = 'text/html';
    const TEXT_JAVASCRIPT = 'text/javascript';
    const TEXT_MCF = 'text/mcf';
    const TEXT_PASCAL = 'text/pascal';
    const TEXT_PLAIN = 'text/plain';
    const TEXT_RICHTEXT = 'text/richtext';
    const TEXT_SCRIPLET = 'text/scriplet';
    const TEXT_SGML = 'text/sgml';
    const TEXT_TAB_SEPARATED_VALUES = 'text/tab-separated-values';
    const TEXT_URI_LIST = 'text/uri-list';
    const TEXT_VNDABC = 'text/vnd.abc';
    const TEXT_VNDFMIFLEXSTOR = 'text/vnd.fmi.flexstor';
    const TEXT_VNDRN_REALTEXT = 'text/vnd.rn-realtext';
    const TEXT_VNDWAPWML = 'text/vnd.wap.wml';
    const TEXT_VNDWAPWMLSCRIPT = 'text/vnd.wap.wmlscript';
    const TEXT_WEBVIEWHTML = 'text/webviewhtml';
    const TEXT_X_ASM = 'text/x-asm';
    const TEXT_X_AUDIOSOFT_INTRA = 'text/x-audiosoft-intra';
    const TEXT_X_C = 'text/x-c';
    const TEXT_X_COMPONENT = 'text/x-component';
    const TEXT_X_FORTRAN = 'text/x-fortran';
    const TEXT_X_H = 'text/x-h';
    const TEXT_X_JAVA_SOURCE = 'text/x-java-source';
    const TEXT_X_LA_ASF = 'text/x-la-asf';
    const TEXT_X_M = 'text/x-m';
    const TEXT_X_PASCAL = 'text/x-pascal';
    const TEXT_X_SCRIPT = 'text/x-script';
    const TEXT_X_SCRIPTCSH = 'text/x-script.csh';
    const TEXT_X_SCRIPTELISP = 'text/x-script.elisp';
    const TEXT_X_SCRIPTGUILE = 'text/x-script.guile';
    const TEXT_X_SCRIPTKSH = 'text/x-script.ksh';
    const TEXT_X_SCRIPTLISP = 'text/x-script.lisp';
    const TEXT_X_SCRIPTPERL = 'text/x-script.perl';
    const TEXT_X_SCRIPTPERL_MODULE = 'text/x-script.perl-module';
    const TEXT_X_SCRIPTPHYTON = 'text/x-script.phyton';
    const TEXT_X_SCRIPTREXX = 'text/x-script.rexx';
    const TEXT_X_SCRIPTSCHEME = 'text/x-script.scheme';
    const TEXT_X_SCRIPTSH = 'text/x-script.sh';
    const TEXT_X_SCRIPTTCL = 'text/x-script.tcl';
    const TEXT_X_SCRIPTTCSH = 'text/x-script.tcsh';
    const TEXT_X_SCRIPTZSH = 'text/x-script.zsh';
    const TEXT_X_SERVER_PARSED_HTML = 'text/x-server-parsed-html';
    const TEXT_X_SETEXT = 'text/x-setext';
    const TEXT_X_SGML = 'text/x-sgml';
    const TEXT_X_SPEECH = 'text/x-speech';
    const TEXT_X_UIL = 'text/x-uil';
    const TEXT_X_UUENCODE = 'text/x-uuencode';
    const TEXT_X_VCALENDAR = 'text/x-vcalendar';
    const TEXT_XML = 'text/xml';
    const VIDEO_ANIMAFLEX = 'video/animaflex';
    const VIDEO_AVI = 'video/avi';
    const VIDEO_AVS_VIDEO = 'video/avs-video';
    const VIDEO_DL = 'video/dl';
    const VIDEO_FLI = 'video/fli';
    const VIDEO_GL = 'video/gl';
    const VIDEO_MPEG = 'video/mpeg';
    const VIDEO_MSVIDEO = 'video/msvideo';
    const VIDEO_QUICKTIME = 'video/quicktime';
    const VIDEO_VDO = 'video/vdo';
    const VIDEO_VIVO = 'video/vivo';
    const VIDEO_VNDRN_REALVIDEO = 'video/vnd.rn-realvideo';
    const VIDEO_VNDVIVO = 'video/vnd.vivo';
    const VIDEO_VOSAIC = 'video/vosaic';
    const VIDEO_X_AMT_DEMORUN = 'video/x-amt-demorun';
    const VIDEO_X_AMT_SHOWRUN = 'video/x-amt-showrun';
    const VIDEO_X_ATOMIC3D_FEATURE = 'video/x-atomic3d-feature';
    const VIDEO_X_DL = 'video/x-dl';
    const VIDEO_X_DV = 'video/x-dv';
    const VIDEO_X_FLI = 'video/x-fli';
    const VIDEO_X_GL = 'video/x-gl';
    const VIDEO_X_ISVIDEO = 'video/x-isvideo';
    const VIDEO_X_MOTION_JPEG = 'video/x-motion-jpeg';
    const VIDEO_X_MPEG = 'video/x-mpeg';
    const VIDEO_X_MPEQ2A = 'video/x-mpeq2a';
    const VIDEO_X_MS_ASF = 'video/x-ms-asf';
    const VIDEO_X_MS_ASF_PLUGIN = 'video/x-ms-asf-plugin';
    const VIDEO_X_MSVIDEO = 'video/x-msvideo';
    const VIDEO_X_QTC = 'video/x-qtc';
    const VIDEO_X_SCM = 'video/x-scm';
    const VIDEO_X_SGI_MOVIE = 'video/x-sgi-movie';
    const WINDOWS_METAFILE = 'windows/metafile';
    const WWW_MIME = 'www/mime';
    const X_CONFERENCE_X_COOLTALK = 'x-conference/x-cooltalk';
    const X_MUSIC_X_MIDI = 'x-music/x-midi';
    const X_WORLD_X_3DMF = 'x-world/x-3dmf';
    const X_WORLD_X_SVR = 'x-world/x-svr';
    const X_WORLD_X_VRML = 'x-world/x-vrml';
    const X_WORLD_X_VRT = 'x-world/x-vrt';
    const XGL_DRAWING = 'xgl/drawing';
    const XGL_MOVIE = 'xgl/movie';

    public static $MYMETYPE_EXTENSIONS = [
        self::APPLICATION_ACAD => ['.dwg'],
        self::APPLICATION_ARJ => ['.arj'],
        self::APPLICATION_BASE64 => ['.mm', '.mme'],
        self::APPLICATION_BINHEX => ['.hqx'],
        self::APPLICATION_BINHEX4 => ['.hqx'],
        self::APPLICATION_BOOK => ['.boo', '.book'],
        self::APPLICATION_CDF => ['.cdf'],
        self::APPLICATION_CLARISCAD => ['.ccad'],
        self::APPLICATION_COMMONGROUND => ['.dp'],
        self::APPLICATION_DRAFTING => ['.drw'],
        self::APPLICATION_DSPTYPE => ['.tsp'],
        self::APPLICATION_DXF => ['.dxf'],
        self::APPLICATION_ECMASCRIPT => ['.js'],
        self::APPLICATION_ENVOY => ['.evy'],
        self::APPLICATION_EXCEL => ['.xls', '.xlt', '.xlw', '.xll', '.xlb', '.xlm', '.xlc', '.xla', '.xlk', '.xld', '.xlv', '.xl'],
        self::APPLICATION_FRACTALS => ['.fif'],
        self::APPLICATION_FREELOADER => ['.frl'],
        self::APPLICATION_FUTURESPLASH => ['.spl'],
        self::APPLICATION_GNUTAR => ['.tgz'],
        self::APPLICATION_GROUPWISE => ['.vew'],
        self::APPLICATION_HLP => ['.hlp'],
        self::APPLICATION_HTA => ['.hta'],
        self::APPLICATION_IGES => ['.iges', '.igs'],
        self::APPLICATION_INF => ['.inf'],
        self::APPLICATION_I_DEAS => ['.unv'],
        self::APPLICATION_JAVA => ['.class'],
        self::APPLICATION_JAVASCRIPT => ['.js'],
        self::APPLICATION_JAVA_BYTE_CODE => ['.class'],
        self::APPLICATION_LHA => ['.lha'],
        self::APPLICATION_LZX => ['.lzx'],
        self::APPLICATION_MACBINARY => ['.bin'],
        self::APPLICATION_MAC_BINARY => ['.bin'],
        self::APPLICATION_MAC_BINHEX => ['.hqx'],
        self::APPLICATION_MAC_BINHEX40 => ['.hqx'],
        self::APPLICATION_MAC_COMPACTPRO => ['.cpt'],
        self::APPLICATION_MARC => ['.mrc'],
        self::APPLICATION_MBEDLET => ['.mbd'],
        self::APPLICATION_MCAD => ['.mcd'],
        self::APPLICATION_MIME => ['.aps'],
        self::APPLICATION_MSPOWERPOINT => ['.ppt', '.pps', '.pot', '.ppz'],
        self::APPLICATION_MSWORD => ['.doc', '.dot', '.w6w', '.wiz', '.word'],
        self::APPLICATION_MSWRITE => ['.wri'],
        self::APPLICATION_NETMC => ['.mcp'],
        self::APPLICATION_OCTET_STREAM => ['.bin', '.com', '.psd', '.exe', '.o', '.lha', '.lzx', '.arj', '.uu', '.lzh', '.arc', '.a', '.zoo', '.lhx', '.saveme', '.dump'],
        self::APPLICATION_ODA => ['.oda'],
        self::APPLICATION_PDF => ['.pdf'],
        self::APPLICATION_PKCS10 => ['.p10'],
        self::APPLICATION_PKCS7_MIME => ['.p7c', '.p7m'],
        self::APPLICATION_PKCS7_SIGNATURE => ['.p7s'],
        self::APPLICATION_PKCS_12 => ['.p12'],
        self::APPLICATION_PKCS_CRL => ['.crl'],
        self::APPLICATION_PKIX_CERT => ['.cer', '.crt'],
        self::APPLICATION_PKIX_CRL => ['.crl'],
        self::APPLICATION_PLAIN => ['.text'],
        self::APPLICATION_POSTSCRIPT => ['.eps', '.ps', '.ai'],
        self::APPLICATION_POWERPOINT => ['.ppt'],
        self::APPLICATION_PRO_ENG => ['.part', '.prt'],
        self::APPLICATION_RINGING_TONES => ['.rng'],
        self::APPLICATION_RTF => ['.rtf', '.rtx'],
        self::APPLICATION_SDP => ['.sdp'],
        self::APPLICATION_SEA => ['.sea'],
        self::APPLICATION_SET => ['.set'],
        self::APPLICATION_SLA => ['.stl'],
        self::APPLICATION_SMIL => ['.smi', '.smil'],
        self::APPLICATION_SOLIDS => ['.sol'],
        self::APPLICATION_SOUNDER => ['.sdr'],
        self::APPLICATION_STEP => ['.step', '.stp'],
        self::APPLICATION_STREAMINGMEDIA => ['.ssm'],
        self::APPLICATION_TOOLBOOK => ['.tbk'],
        self::APPLICATION_VDA => ['.vda'],
        self::APPLICATION_VNDFDF => ['.fdf'],
        self::APPLICATION_VNDHP_HPGL => ['.hgl', '.hpg', '.hpgl'],
        self::APPLICATION_VNDHP_PCL => ['.pcl'],
        self::APPLICATION_VNDMS_EXCEL => ['.xls', '.xlw', '.xlc', '.xll', '.xlb', '.xlm'],
        self::APPLICATION_VNDMS_PKICERTSTORE => ['.sst'],
        self::APPLICATION_VNDMS_PKIPKO => ['.pko'],
        self::APPLICATION_VNDMS_PKISECCAT => ['.cat'],
        self::APPLICATION_VNDMS_PKISTL => ['.stl'],
        self::APPLICATION_VNDMS_POWERPOINT => ['.ppt', '.pps', '.pot', '.ppa', '.pwz'],
        self::APPLICATION_VNDMS_PROJECT => ['.mpp'],
        self::APPLICATION_VNDNOKIACONFIGURATION_MESSAGE => ['.ncm'],
        self::APPLICATION_VNDNOKIARINGING_TONE => ['.rng'],
        self::APPLICATION_VNDRN_REALMEDIA => ['.rm'],
        self::APPLICATION_VNDRN_REALPLAYER => ['.rnx'],
        self::APPLICATION_VNDWAPWMLC => ['.wmlc'],
        self::APPLICATION_VNDWAPWMLSCRIPTC => ['.wmlsc'],
        self::APPLICATION_VNDXARA => ['.web'],
        self::APPLICATION_VOCALTEC_MEDIA_DESC => ['.vmd'],
        self::APPLICATION_VOCALTEC_MEDIA_FILE => ['.vmf'],
        self::APPLICATION_WORDPERFECT => ['.wpd', '.wp5', '.wp6', '.wp'],
        self::APPLICATION_WORDPERFECT60 => ['.wp5', '.w60'],
        self::APPLICATION_WORDPERFECT61 => ['.w61'],
        self::APPLICATION_XML => ['.xml'],
        self::APPLICATION_X_123 => ['.wk1'],
        self::APPLICATION_X_AIM => ['.aim'],
        self::APPLICATION_X_AUTHORWARE_BIN => ['.aab'],
        self::APPLICATION_X_AUTHORWARE_MAP => ['.aam'],
        self::APPLICATION_X_AUTHORWARE_SEG => ['.aas'],
        self::APPLICATION_X_BCPIO => ['.bcpio'],
        self::APPLICATION_X_BINARY => ['.bin'],
        self::APPLICATION_X_BINHEX40 => ['.hqx'],
        self::APPLICATION_X_BSH => ['.sh', '.shar', '.bsh'],
        self::APPLICATION_X_BYTECODEPYTHON => ['.pyc'],
        self::APPLICATION_X_BZIP => ['.bz'],
        self::APPLICATION_X_BZIP2 => ['.bz2', '.boz'],
        self::APPLICATION_X_CDF => ['.cdf'],
        self::APPLICATION_X_CDLINK => ['.vcd'],
        self::APPLICATION_X_CHAT => ['.cha', '.chat'],
        self::APPLICATION_X_CMU_RASTER => ['.ras'],
        self::APPLICATION_X_COCOA => ['.cco'],
        self::APPLICATION_X_COMPACTPRO => ['.cpt'],
        self::APPLICATION_X_COMPRESS => ['.z'],
        self::APPLICATION_X_COMPRESSED => ['.zip', '.gz', '.tgz', '.z'],
        self::APPLICATION_X_CONFERENCE => ['.nsc'],
        self::APPLICATION_X_CPIO => ['.cpio'],
        self::APPLICATION_X_CPT => ['.cpt'],
        self::APPLICATION_X_CSH => ['.csh'],
        self::APPLICATION_X_DEEPV => ['.deepv'],
        self::APPLICATION_X_DIRECTOR => ['.dir', '.dxr', '.dcr'],
        self::APPLICATION_X_DVI => ['.dvi'],
        self::APPLICATION_X_ELC => ['.elc'],
        self::APPLICATION_X_ENVOY => ['.evy', '.env'],
        self::APPLICATION_X_ESREHBER => ['.es'],
        self::APPLICATION_X_EXCEL => ['.xls', '.xlt', '.xlw', '.xlc', '.xlb', '.xll', '.xla', '.xlm', '.xld', '.xlv', '.xlk'],
        self::APPLICATION_X_FRAME => ['.mif'],
        self::APPLICATION_X_FREELANCE => ['.pre'],
        self::APPLICATION_X_GSP => ['.gsp'],
        self::APPLICATION_X_GSS => ['.gss'],
        self::APPLICATION_X_GTAR => ['.gtar'],
        self::APPLICATION_X_GZIP => ['.gz', '.gzip'],
        self::APPLICATION_X_HDF => ['.hdf'],
        self::APPLICATION_X_HELPFILE => ['.hlp', '.help'],
        self::APPLICATION_X_HTTPD_IMAP => ['.imap'],
        self::APPLICATION_X_IMA => ['.ima'],
        self::APPLICATION_X_INTERNETT_SIGNUP => ['.ins'],
        self::APPLICATION_X_INVENTOR => ['.iv'],
        self::APPLICATION_X_IP2 => ['.ip'],
        self::APPLICATION_X_JAVASCRIPT => ['.js'],
        self::APPLICATION_X_JAVA_CLASS => ['.class'],
        self::APPLICATION_X_JAVA_COMMERCE => ['.jcm'],
        self::APPLICATION_X_KOAN => ['.skd', '.skm', '.skp', '.skt'],
        self::APPLICATION_X_KSH => ['.ksh'],
        self::APPLICATION_X_LATEX => ['.latex', '.ltx'],
        self::APPLICATION_X_LHA => ['.lha'],
        self::APPLICATION_X_LISP => ['.lsp'],
        self::APPLICATION_X_LIVESCREEN => ['.ivy'],
        self::APPLICATION_X_LOTUS => ['.wq1'],
        self::APPLICATION_X_LOTUSSCREENCAM => ['.scm'],
        self::APPLICATION_X_LZH => ['.lzh'],
        self::APPLICATION_X_LZX => ['.lzx'],
        self::APPLICATION_X_MACBINARY => ['.bin'],
        self::APPLICATION_X_MAC_BINHEX40 => ['.hqx'],
        self::APPLICATION_X_MATHCAD => ['.mcd'],
        self::APPLICATION_X_MEME => ['.mm'],
        self::APPLICATION_X_MIDI => ['.mid', '.midi'],
        self::APPLICATION_X_MIF => ['.mif'],
        self::APPLICATION_X_MIX_TRANSFER => ['.nix'],
        self::APPLICATION_X_MPLAYER2 => ['.asx'],
        self::APPLICATION_X_MSEXCEL => ['.xls', '.xlw', '.xla'],
        self::APPLICATION_X_MSPOWERPOINT => ['.ppt'],
        self::APPLICATION_X_NAVIDOC => ['.nvd'],
        self::APPLICATION_X_NAVIMAP => ['.map'],
        self::APPLICATION_X_NAVISTYLE => ['.stl'],
        self::APPLICATION_X_NAVI_ANIMATION => ['.ani'],
        self::APPLICATION_X_NETCDF => ['.cdf', '.nc'],
        self::APPLICATION_X_NEWTON_COMPATIBLE_PKG => ['.pkg'],
        self::APPLICATION_X_NOKIA_9000_COMMUNICATOR_ADD_ON_SOFTWARE => ['.aos'],
        self::APPLICATION_X_OMC => ['.omc'],
        self::APPLICATION_X_OMCDATAMAKER => ['.omcd'],
        self::APPLICATION_X_OMCREGERATOR => ['.omcr'],
        self::APPLICATION_X_PAGEMAKER => ['.pm4', '.pm5'],
        self::APPLICATION_X_PCL => ['.pcl'],
        self::APPLICATION_X_PIXCLSCRIPT => ['.plx'],
        self::APPLICATION_X_PKCS10 => ['.p10'],
        self::APPLICATION_X_PKCS12 => ['.p12'],
        self::APPLICATION_X_PKCS7_CERTIFICATES => ['.spc'],
        self::APPLICATION_X_PKCS7_CERTREQRESP => ['.p7r'],
        self::APPLICATION_X_PKCS7_MIME => ['.p7c', '.p7m'],
        self::APPLICATION_X_PKCS7_SIGNATURE => ['.p7a'],
        self::APPLICATION_X_POINTPLUS => ['.css'],
        self::APPLICATION_X_PORTABLE_ANYMAP => ['.pnm'],
        self::APPLICATION_X_PROJECT => ['.mpc', '.mpt', '.mpv', '.mpx'],
        self::APPLICATION_X_QPRO => ['.wb1'],
        self::APPLICATION_X_RTF => ['.rtf'],
        self::APPLICATION_X_SDP => ['.sdp'],
        self::APPLICATION_X_SEA => ['.sea'],
        self::APPLICATION_X_SEELOGO => ['.sl'],
        self::APPLICATION_X_SH => ['.sh'],
        self::APPLICATION_X_SHAR => ['.sh', '.shar'],
        self::APPLICATION_X_SHOCKWAVE_FLASH => ['.swf'],
        self::APPLICATION_X_SIT => ['.sit'],
        self::APPLICATION_X_SPRITE => ['.spr', '.sprite'],
        self::APPLICATION_X_STUFFIT => ['.sit'],
        self::APPLICATION_X_SV4CPIO => ['.sv4cpio'],
        self::APPLICATION_X_SV4CRC => ['.sv4crc'],
        self::APPLICATION_X_TAR => ['.tar'],
        self::APPLICATION_X_TBOOK => ['.tbk', '.sbk'],
        self::APPLICATION_X_TCL => ['.tcl'],
        self::APPLICATION_X_TEX => ['.tex'],
        self::APPLICATION_X_TEXINFO => ['.texi', '.texinfo'],
        self::APPLICATION_X_TROFF => ['.roff', '.t', '.tr'],
        self::APPLICATION_X_TROFF_MAN => ['.man'],
        self::APPLICATION_X_TROFF_ME => ['.me'],
        self::APPLICATION_X_TROFF_MS => ['.ms'],
        self::APPLICATION_X_TROFF_MSVIDEO => ['.avi'],
        self::APPLICATION_X_USTAR => ['.ustar'],
        self::APPLICATION_X_VISIO => ['.vsd', '.vst', '.vsw'],
        self::APPLICATION_X_VNDAUDIOEXPLOSIONMZZ => ['.mzz'],
        self::APPLICATION_X_VNDLS_XPIX => ['.xpix'],
        self::APPLICATION_X_VRML => ['.vrml'],
        self::APPLICATION_X_WAIS_SOURCE => ['.src', '.wsrc'],
        self::APPLICATION_X_WINHELP => ['.hlp'],
        self::APPLICATION_X_WINTALK => ['.wtk'],
        self::APPLICATION_X_WORLD => ['.wrl', '.svr'],
        self::APPLICATION_X_WPWIN => ['.wpd'],
        self::APPLICATION_X_WRI => ['.wri'],
        self::APPLICATION_X_X509_CA_CERT => ['.cer', '.crt', '.der'],
        self::APPLICATION_X_X509_USER_CERT => ['.crt'],
        self::APPLICATION_X_ZIP_COMPRESSED => ['.zip'],
        self::APPLICATION_ZIP => ['.zip'],
        self::AUDIO_AIFF => ['.aif', '.aifc', '.aiff'],
        self::AUDIO_BASIC => ['.au', '.snd'],
        self::AUDIO_IT => ['.it'],
        self::AUDIO_MAKE => ['.pfunk', '.my', '.funk'],
        self::AUDIO_MAKEMYFUNK => ['.pfunk'],
        self::AUDIO_MID => ['.rmi'],
        self::AUDIO_MIDI => ['.mid', '.midi', '.kar'],
        self::AUDIO_MOD => ['.mod'],
        self::AUDIO_MPEG => ['.mpg', '.mp2', '.mpa', '.m2a', '.mpga'],
        self::AUDIO_MPEG3 => ['.mp3'],
        self::AUDIO_NSPAUDIO => ['.la', '.lma'],
        self::AUDIO_S3M => ['.s3m'],
        self::AUDIO_TSPLAYER => ['.tsp'],
        self::AUDIO_TSP_AUDIO => ['.tsi'],
        self::AUDIO_VNDQCELP => ['.qcp'],
        self::AUDIO_VOC => ['.voc'],
        self::AUDIO_VOXWARE => ['.vox'],
        self::AUDIO_WAV => ['.wav'],
        self::AUDIO_XM => ['.xm'],
        self::AUDIO_X_ADPCM => ['.snd'],
        self::AUDIO_X_AIFF => ['.aif', '.aifc', '.aiff'],
        self::AUDIO_X_AU => ['.au'],
        self::AUDIO_X_GSM => ['.gsd', '.gsm'],
        self::AUDIO_X_JAM => ['.jam'],
        self::AUDIO_X_LIVEAUDIO => ['.lam'],
        self::AUDIO_X_MID => ['.mid', '.midi'],
        self::AUDIO_X_MIDI => ['.mid', '.midi'],
        self::AUDIO_X_MOD => ['.mod'],
        self::AUDIO_X_MPEG => ['.mp2'],
        self::AUDIO_X_MPEG_3 => ['.mp3'],
        self::AUDIO_X_MPEQURL => ['.m3u'],
        self::AUDIO_X_NSPAUDIO => ['.la', '.lma'],
        self::AUDIO_X_PN_REALAUDIO => ['.rm', '.ram', '.ra', '.rmp', '.rmm'],
        self::AUDIO_X_PN_REALAUDIO_PLUGIN => ['.rpm', '.ra', '.rmp'],
        self::AUDIO_X_PSID => ['.sid'],
        self::AUDIO_X_REALAUDIO => ['.ra'],
        self::AUDIO_X_TWINVQ => ['.vqf'],
        self::AUDIO_X_TWINVQ_PLUGIN => ['.vqe', '.vql'],
        self::AUDIO_X_VNDAUDIOEXPLOSIONMJUICEMEDIAFILE => ['.mjf'],
        self::AUDIO_X_VOC => ['.voc'],
        self::AUDIO_X_WAV => ['.wav'],
        self::CHEMICAL_X_PDB => ['.pdb', '.xyz'],
        self::IMAGE_BMP => ['.bmp', '.bm'],
        self::IMAGE_CMU_RASTER => ['.ras', '.rast'],
        self::IMAGE_FIF => ['.fif'],
        self::IMAGE_FLORIAN => ['.flo', '.turbot'],
        self::IMAGE_G3FAX => ['.g3'],
        self::IMAGE_GIF => ['.gif'],
        self::IMAGE_IEF => ['.ief', '.iefs'],
        self::IMAGE_JPEG => ['.jpg', '.jpeg', '.jpe', '.jfif', '.jfif-tbnl'],
        self::IMAGE_JUTVISION => ['.jut'],
        self::IMAGE_NAPLPS => ['.nap', '.naplps'],
        self::IMAGE_PICT => ['.pic', '.pict'],
        self::IMAGE_PJPEG => ['.jpg', '.jpeg', '.jpe', '.jfif'],
        self::IMAGE_PNG => ['.png', '.x-png'],
        self::IMAGE_TIFF => ['.tiff', '.tif'],
        self::IMAGE_VASA => ['.mcf'],
        self::IMAGE_VNDDWG => ['.dwg', '.dxf', '.svf'],
        self::IMAGE_VNDFPX => ['.fpx'],
        self::IMAGE_VNDNET_FPX => ['.fpx'],
        self::IMAGE_VNDRN_REALFLASH => ['.rf'],
        self::IMAGE_VNDRN_REALPIX => ['.rp'],
        self::IMAGE_VNDWAPWBMP => ['.wbmp'],
        self::IMAGE_VNDXIFF => ['.xif'],
        self::IMAGE_XBM => ['.xbm'],
        self::IMAGE_XPM => ['.xpm'],
        self::IMAGE_X_CMU_RASTER => ['.ras'],
        self::IMAGE_X_DWG => ['.dwg', '.dxf', '.svf'],
        self::IMAGE_X_ICON => ['.ico'],
        self::IMAGE_X_JG => ['.art'],
        self::IMAGE_X_JPS => ['.jps'],
        self::IMAGE_X_NIFF => ['.nif', '.niff'],
        self::IMAGE_X_PCX => ['.pcx'],
        self::IMAGE_X_PICT => ['.pct'],
        self::IMAGE_X_PORTABLE_ANYMAP => ['.pnm'],
        self::IMAGE_X_PORTABLE_BITMAP => ['.pbm'],
        self::IMAGE_X_PORTABLE_GRAYMAP => ['.pgm'],
        self::IMAGE_X_PORTABLE_GREYMAP => ['.pgm'],
        self::IMAGE_X_PORTABLE_PIXMAP => ['.ppm'],
        self::IMAGE_X_QUICKTIME => ['.qif', '.qti', '.qtif'],
        self::IMAGE_X_RGB => ['.rgb'],
        self::IMAGE_X_TIFF => ['.tiff', '.tif'],
        self::IMAGE_X_WINDOWS_BMP => ['.bmp'],
        self::IMAGE_X_XBITMAP => ['.xbm'],
        self::IMAGE_X_XBM => ['.xbm'],
        self::IMAGE_X_XPIXMAP => ['.pm', '.xpm'],
        self::IMAGE_X_XWD => ['.xwd'],
        self::IMAGE_X_XWINDOWDUMP => ['.xwd'],
        self::I_WORLD_I_VRML => ['.ivr'],
        self::MESSAGE_RFC822 => ['.mime', '.mhtml', '.mht'],
        self::MODEL_IGES => ['.iges', '.igs'],
        self::MODEL_VNDDWF => ['.dwf'],
        self::MODEL_VRML => ['.vrml', '.wrl', '.wrz'],
        self::MODEL_X_POV => ['.pov'],
        self::MULTIPART_X_GZIP => ['.gzip'],
        self::MULTIPART_X_USTAR => ['.ustar'],
        self::MULTIPART_X_ZIP => ['.zip'],
        self::MUSIC_CRESCENDO => ['.mid', '.midi'],
        self::MUSIC_X_KARAOKE => ['.kar'],
        self::PALEOVU_X_PV => ['.pvu'],
        self::TEXT_ASP => ['.asp'],
        self::TEXT_CSS => ['.css'],
        self::TEXT_ECMASCRIPT => ['.js'],
        self::TEXT_HTML => ['.htm', '.html', '.shtml', '.htmls', '.htx', '.acgi'],
        self::TEXT_JAVASCRIPT => ['.js'],
        self::TEXT_MCF => ['.mcf'],
        self::TEXT_PASCAL => ['.pas'],
        self::TEXT_PLAIN => ['.txt', '.pl', '.com', '.c', '.log', '.mar', '.h', '.java', '.m', '.c++', '.cc', '.for', '.f90', '.f', '.hh', '.jav', '.text', '.lst', '.sdml', '.g', '.conf', '.cxx', '.idc', '.list', '.def'],
        self::TEXT_RICHTEXT => ['.rtf', '.rtx', '.rt'],
        self::TEXT_SCRIPLET => ['.wsc'],
        self::TEXT_SGML => ['.sgml', '.sgm'],
        self::TEXT_TAB_SEPARATED_VALUES => ['.tsv'],
        self::TEXT_URI_LIST => ['.uni', '.unis', '.uri', '.uris'],
        self::TEXT_VNDABC => ['.abc'],
        self::TEXT_VNDFMIFLEXSTOR => ['.flx'],
        self::TEXT_VNDRN_REALTEXT => ['.rt'],
        self::TEXT_VNDWAPWML => ['.wml'],
        self::TEXT_VNDWAPWMLSCRIPT => ['.wmls'],
        self::TEXT_WEBVIEWHTML => ['.htt'],
        self::TEXT_XML => ['.xml'],
        self::TEXT_X_ASM => ['.asm', '.s'],
        self::TEXT_X_AUDIOSOFT_INTRA => ['.aip'],
        self::TEXT_X_C => ['.c', '.cpp', '.cc'],
        self::TEXT_X_COMPONENT => ['.htc'],
        self::TEXT_X_FORTRAN => ['.f', '.f90', '.for', '.f77'],
        self::TEXT_X_H => ['.h', '.hh'],
        self::TEXT_X_JAVA_SOURCE => ['.java', '.jav'],
        self::TEXT_X_LA_ASF => ['.lsx'],
        self::TEXT_X_M => ['.m'],
        self::TEXT_X_PASCAL => ['.p'],
        self::TEXT_X_SCRIPT => ['.hlb'],
        self::TEXT_X_SCRIPTCSH => ['.csh'],
        self::TEXT_X_SCRIPTELISP => ['.el'],
        self::TEXT_X_SCRIPTGUILE => ['.scm'],
        self::TEXT_X_SCRIPTKSH => ['.ksh'],
        self::TEXT_X_SCRIPTLISP => ['.lsp'],
        self::TEXT_X_SCRIPTPERL => ['.pl'],
        self::TEXT_X_SCRIPTPERL_MODULE => ['.pm'],
        self::TEXT_X_SCRIPTPHYTON => ['.py'],
        self::TEXT_X_SCRIPTREXX => ['.rexx'],
        self::TEXT_X_SCRIPTSCHEME => ['.scm'],
        self::TEXT_X_SCRIPTSH => ['.sh'],
        self::TEXT_X_SCRIPTTCL => ['.tcl'],
        self::TEXT_X_SCRIPTTCSH => ['.tcsh'],
        self::TEXT_X_SCRIPTZSH => ['.zsh'],
        self::TEXT_X_SERVER_PARSED_HTML => ['.shtml', '.ssi'],
        self::TEXT_X_SETEXT => ['.etx'],
        self::TEXT_X_SGML => ['.sgml', '.sgm'],
        self::TEXT_X_SPEECH => ['.spc', '.talk'],
        self::TEXT_X_UIL => ['.uil'],
        self::TEXT_X_UUENCODE => ['.uue', '.uu'],
        self::TEXT_X_VCALENDAR => ['.vcs'],
        self::VIDEO_ANIMAFLEX => ['.afl'],
        self::VIDEO_AVI => ['.avi'],
        self::VIDEO_AVS_VIDEO => ['.avs'],
        self::VIDEO_DL => ['.dl'],
        self::VIDEO_FLI => ['.fli'],
        self::VIDEO_GL => ['.gl'],
        self::VIDEO_MPEG => ['.mpg', '.mpeg', '.mp2', '.mp3', '.mpa', '.m2v', '.mpe', '.m1v'],
        self::VIDEO_MSVIDEO => ['.avi'],
        self::VIDEO_QUICKTIME => ['.mov', '.qt', '.moov'],
        self::VIDEO_VDO => ['.vdo'],
        self::VIDEO_VIVO => ['.viv', '.vivo'],
        self::VIDEO_VNDRN_REALVIDEO => ['.rv'],
        self::VIDEO_VNDVIVO => ['.viv', '.vivo'],
        self::VIDEO_VOSAIC => ['.vos'],
        self::VIDEO_X_AMT_DEMORUN => ['.xdr'],
        self::VIDEO_X_AMT_SHOWRUN => ['.xsr'],
        self::VIDEO_X_ATOMIC3D_FEATURE => ['.fmf'],
        self::VIDEO_X_DL => ['.dl'],
        self::VIDEO_X_DV => ['.dif', '.dv'],
        self::VIDEO_X_FLI => ['.fli'],
        self::VIDEO_X_GL => ['.gl'],
        self::VIDEO_X_ISVIDEO => ['.isu'],
        self::VIDEO_X_MOTION_JPEG => ['.mjpg'],
        self::VIDEO_X_MPEG => ['.mp2', '.mp3'],
        self::VIDEO_X_MPEQ2A => ['.mp2'],
        self::VIDEO_X_MSVIDEO => ['.avi'],
        self::VIDEO_X_MS_ASF => ['.asf', '.asx'],
        self::VIDEO_X_MS_ASF_PLUGIN => ['.asx'],
        self::VIDEO_X_QTC => ['.qtc'],
        self::VIDEO_X_SCM => ['.scm'],
        self::VIDEO_X_SGI_MOVIE => ['.movie', '.mv'],
        self::WINDOWS_METAFILE => ['.wmf'],
        self::WWW_MIME => ['.mime'],
        self::XGL_DRAWING => ['.xgz'],
        self::XGL_MOVIE => ['.xmz'],
        self::X_CONFERENCE_X_COOLTALK => ['.ice'],
        self::X_MUSIC_X_MIDI => ['.mid', '.midi'],
        self::X_WORLD_X_3DMF => ['.3dm', '.3dmf', '.qd3', '.qd3d'],
        self::X_WORLD_X_SVR => ['.svr'],
        self::X_WORLD_X_VRML => ['.vrml', '.wrl', '.wrz'],
        self::X_WORLD_X_VRT => ['.vrt']
    ];

    public static function isValidMimeType($mimeType){
        return isset(self::$MYMETYPE_EXTENSIONS[$mimeType]);
    }

    /**
     * @param $mimeType
     * @return array|null
     */
    public static function extensionsOfMimeType($mimeType) {
        if(self::isValidMimeType($mimeType)){
            return self::$MYMETYPE_EXTENSIONS[$mimeType];
        }
        return null;
    }

    /**
     * Pretty much time consuming, but returns all the mime types that match that extension
     * Extension must have preceding point to work
     * @param $extension
     * @return array
     */
    public static function mimeTypesOfExtension($extension) {
        $mimeTypesMatched = [];
        foreach(self::$MYMETYPE_EXTENSIONS as $mime => $extensions){
            if(in_array($extension, $extensions)){
                $mimeTypesMatched[] = $mime;
            }
        }
        return $mimeTypesMatched;
    }

}